#!/usr/bin/env Rscript

# ==========================================================
# 08_generate_main_figures.R
# Ribeiro Classification Score (RCS)
#
# Main figures:
#   Figure 2 — Synthetic validation heatmap
#   Figure 3 — Combinatorial distribution of admissible grades
#   Figure 4 — Threshold stability and grade-transition matrix
#   Figure 5 — Runtime scalability
#
# Supplementary figures:
#   None generated by design.
#
# Supplementary audit tables:
#   Additional_File_S4 onward, when source tables are available.
#
# Editorial rule:
#   Long captions/titles belong in the manuscript, not inside figures.
# ==========================================================

options(warn = 1, scipen = 999)

# ==========================================================
# 0. Packages
# ==========================================================

required_packages <- c(
  "ggplot2",
  "dplyr",
  "tidyr",
  "readr",
  "stringr",
  "scales",
  "patchwork"
)

missing_packages <- required_packages[
  !vapply(required_packages, requireNamespace, logical(1), quietly = TRUE)
]

if (length(missing_packages) > 0) {
  stop(
    "Missing required packages: ",
    paste(missing_packages, collapse = ", "),
    "\nInstall them before running this script."
  )
}

suppressPackageStartupMessages({
  library(ggplot2)
  library(dplyr)
  library(tidyr)
  library(readr)
  library(stringr)
  library(scales)
  library(patchwork)
})

# ==========================================================
# 1. Paths
# ==========================================================

get_project_root <- function() {
  cwd <- normalizePath(getwd(), winslash = "/", mustWork = TRUE)

  if (dir.exists(file.path(cwd, "outputs", "tables"))) {
    return(cwd)
  }

  if (dir.exists(file.path(cwd, "..", "outputs", "tables"))) {
    return(normalizePath(file.path(cwd, ".."), winslash = "/", mustWork = TRUE))
  }

  env_root <- Sys.getenv("RCS_PROJECT_ROOT")
  if (nzchar(env_root) && dir.exists(file.path(env_root, "outputs", "tables"))) {
    return(normalizePath(env_root, winslash = "/", mustWork = TRUE))
  }

  stop(
    "Could not locate project root. Run from project root or set RCS_PROJECT_ROOT."
  )
}

project_root <- get_project_root()

table_dir <- Sys.getenv("RCS_TABLE_DIR")
if (!nzchar(table_dir)) table_dir <- file.path(project_root, "outputs", "tables")

figure_dir <- Sys.getenv("RCS_FIGURE_DIR")
if (!nzchar(figure_dir)) figure_dir <- file.path(project_root, "outputs", "figures")

figure_source_dir <- file.path(table_dir, "figure_source")
supplementary_dir <- file.path(table_dir, "supplementary")

dir.create(figure_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(figure_source_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(supplementary_dir, recursive = TRUE, showWarnings = FALSE)

message("Project root: ", project_root)
message("Table directory: ", table_dir)
message("Figure directory: ", figure_dir)
message("Figure source directory: ", figure_source_dir)
message("Supplementary table directory: ", supplementary_dir)

# ==========================================================
# 2. Visual standard
# ==========================================================

grade_levels <- c("Grade A", "Grade B", "Grade C", "Grade D", "Grade E")
grade_letters <- c("A", "B", "C", "D", "E")

grade_cols <- c(
  "Grade A" = "#78A9FF",
  "Grade B" = "#82CFFF",
  "Grade C" = "#BE95FF",
  "Grade D" = "#FFB784",
  "Grade E" = "#FF8389"
)

grade_cols_strong <- c(
  "Grade A" = "#4589FF",
  "Grade B" = "#33B1FF",
  "Grade C" = "#8A3FFC",
  "Grade D" = "#FF832B",
  "Grade E" = "#FA4D56"
)

severity_cols <- c(
  "#4589FF",
  "#78A9FF",
  "#FFF1C7",
  "#FFB784",
  "#FA4D56"
)

matrix_levels <- c("fluid", "solid")
matrix_labels <- c(
  "fluid" = "Fluid biospecimens",
  "solid" = "Solid biospecimens"
)

scenario_levels <- c(
  "Optimal",
  "Mild suboptimal",
  "Moderate suboptimal",
  "Severe suboptimal",
  "Critical penalty",
  "Governance failure"
)

scenario_labels_manual <- c(
  "Optimal" = "Optimal",
  "Mild suboptimal" = "Mild\nsuboptimal",
  "Moderate suboptimal" = "Moderate\nsuboptimal",
  "Severe suboptimal" = "Severe\nsuboptimal",
  "Critical penalty" = "Critical\npenalty",
  "Governance failure" = "Governance\nfailure"
)

weight_scenario_levels <- c("-20%", "-10%", "Nominal", "+10%", "+20%")

threshold_levels <- c("A to B", "B to C", "C to D", "D to E")
threshold_labels <- c(
  "A to B" = "A\u2192B",
  "B to C" = "B\u2192C",
  "C to D" = "C\u2192D",
  "D to E" = "D\u2192E"
)

theme_rcs <- function(base_size = 13) {
  ggplot2::theme_minimal(base_size = base_size, base_family = "sans") +
    ggplot2::theme(
      plot.background = ggplot2::element_rect(fill = "white", colour = NA),
      panel.background = ggplot2::element_rect(fill = "white", colour = NA),
      panel.grid.major = ggplot2::element_line(colour = "#E0E0E0", linewidth = 0.35),
      panel.grid.minor = ggplot2::element_blank(),
      axis.title = ggplot2::element_text(colour = "#222222", size = base_size + 1),
      axis.text = ggplot2::element_text(colour = "#4A4A4A", size = base_size),
      strip.text = ggplot2::element_text(
        colour = "#222222",
        face = "bold",
        size = base_size + 2,
        margin = ggplot2::margin(b = 6)
      ),
      legend.position = "bottom",
      legend.title = ggplot2::element_text(size = base_size),
      legend.text = ggplot2::element_text(size = base_size - 1),
      legend.box = "vertical",
      legend.margin = ggplot2::margin(t = 6, r = 8, b = 8, l = 8),
      legend.box.margin = ggplot2::margin(t = 6, r = 8, b = 8, l = 8),
      plot.margin = ggplot2::margin(t = 12, r = 18, b = 18, l = 18)
    )
}

theme_rcs_compact <- function(base_size = 11) {
  theme_rcs(base_size = base_size) +
    ggplot2::theme(
      axis.title = ggplot2::element_text(size = base_size + 1),
      axis.text = ggplot2::element_text(size = base_size),
      strip.text = ggplot2::element_text(size = base_size + 1),
      plot.margin = ggplot2::margin(t = 8, r = 8, b = 8, l = 8)
    )
}

# ==========================================================
# 3. Utility functions
# ==========================================================

clean_names <- function(df) {
  names(df) <- names(df) |>
    stringr::str_replace_all("[^A-Za-z0-9]+", "_") |>
    stringr::str_replace_all("_+", "_") |>
    stringr::str_replace_all("^_|_$", "") |>
    tolower()
  df
}

find_col <- function(df, candidates, required = TRUE, label = "column") {
  candidates <- tolower(candidates)
  hit <- intersect(candidates, names(df))

  if (length(hit) == 0) {
    if (required) {
      stop(
        "Could not find required ", label, ". Tried: ",
        paste(candidates, collapse = ", "),
        "\nAvailable columns: ",
        paste(names(df), collapse = ", ")
      )
    }
    return(NA_character_)
  }

  hit[[1]]
}

parse_num <- function(x) {
  if (is.numeric(x)) return(x)

  x_chr <- as.character(x)
  x_chr <- stringr::str_trim(x_chr)

  x_chr <- ifelse(
    stringr::str_detect(x_chr, ",") & !stringr::str_detect(x_chr, "\\."),
    stringr::str_replace_all(x_chr, ",", "."),
    x_chr
  )

  readr::parse_number(x_chr)
}

normalize_matrix <- function(x) {
  x <- tolower(as.character(x))

  dplyr::case_when(
    stringr::str_detect(x, "fluid|fluido") ~ "fluid",
    stringr::str_detect(x, "solid|sólido|solido") ~ "solid",
    TRUE ~ x
  )
}

normalize_grade <- function(x) {
  x <- stringr::str_trim(as.character(x))
  x <- stringr::str_replace_all(x, "Category", "Grade")
  x <- stringr::str_replace_all(x, "grade", "Grade")
  x <- stringr::str_replace_all(x, "^([A-E])$", "Grade \\1")
  x <- stringr::str_replace_all(x, "^Grade\\s*([A-E]).*$", "Grade \\1")
  x
}

normalize_scenario <- function(x) {
  x0 <- tolower(as.character(x))
  x0 <- stringr::str_replace_all(x0, "_", " ")
  x0 <- stringr::str_squish(x0)

  dplyr::case_when(
    stringr::str_detect(x0, "optimal") &
      !stringr::str_detect(x0, "mild|moderate|severe") ~ "Optimal",
    stringr::str_detect(x0, "mild") ~ "Mild suboptimal",
    stringr::str_detect(x0, "moderate") ~ "Moderate suboptimal",
    stringr::str_detect(x0, "severe") ~ "Severe suboptimal",
    stringr::str_detect(x0, "critical") ~ "Critical penalty",
    stringr::str_detect(x0, "governance") ~ "Governance failure",
    TRUE ~ stringr::str_to_sentence(x0)
  )
}

score_grade <- function(rcs) {
  dplyr::case_when(
    rcs >= 90 ~ "Grade A",
    rcs >= 80 ~ "Grade B",
    rcs >= 65 ~ "Grade C",
    rcs >= 50 ~ "Grade D",
    TRUE ~ "Grade E"
  )
}

profile_label <- function(x) {
  dplyr::case_when(
    x == 0 ~ "0",
    abs(x) >= 1e6 ~ paste0(format(round(x / 1e6, 1), nsmall = 1), "M"),
    TRUE ~ scales::comma(x)
  )
}

find_table_file <- function(stem, optional = FALSE) {
  pattern <- paste0("^", stem, "(\\([0-9]+\\))?\\.csv$")
  files <- list.files(table_dir, pattern = pattern, full.names = TRUE)

  if (length(files) == 0) {
    files <- list.files(
      table_dir,
      pattern = paste0(stem, ".*\\.csv$"),
      full.names = TRUE,
      ignore.case = TRUE
    )
  }

  if (length(files) == 0) {
    if (optional) return(NA_character_)
    stop("Required table not found: ", stem, ".csv in ", table_dir)
  }

  files[[1]]
}

read_table_clean <- function(stem, optional = FALSE) {
  path <- find_table_file(stem, optional = optional)

  if (is.na(path)) return(NULL)

  message("Reading table: ", basename(path))

  readr::read_csv(path, show_col_types = FALSE, progress = FALSE) |>
    clean_names()
}

read_table_raw_by_stem <- function(stem) {
  path <- find_table_file(stem, optional = TRUE)

  if (is.na(path)) return(NULL)

  readr::read_csv(path, show_col_types = FALSE, progress = FALSE)
}

save_figure <- function(plot, filename, width, height) {
  pdf_file <- file.path(figure_dir, paste0(filename, ".pdf"))
  png_file <- file.path(figure_dir, paste0(filename, ".png"))

  pdf_device <- if (capabilities("cairo")) grDevices::cairo_pdf else grDevices::pdf

  ggplot2::ggsave(
    filename = pdf_file,
    plot = plot,
    width = width,
    height = height,
    units = "in",
    device = pdf_device,
    bg = "white",
    limitsize = FALSE
  )

  ggplot2::ggsave(
    filename = png_file,
    plot = plot,
    width = width,
    height = height,
    units = "in",
    dpi = 600,
    bg = "white",
    limitsize = FALSE
  )

  message("Saved: ", pdf_file)
  message("Saved: ", png_file)
}

make_text_plot <- function(label, size = 4.2, face = "bold", hjust = 0) {
  ggplot2::ggplot() +
    ggplot2::annotate(
      "text",
      x = ifelse(hjust == 0.5, 0.5, 0),
      y = 0.5,
      label = label,
      hjust = hjust,
      vjust = 0.5,
      size = size,
      fontface = face,
      colour = "#222222",
      lineheight = 0.95
    ) +
    ggplot2::coord_cartesian(xlim = c(0, 1), ylim = c(0, 1), clip = "off") +
    ggplot2::theme_void() +
    ggplot2::theme(
      plot.margin = ggplot2::margin(t = 2, r = 6, b = 2, l = 6)
    )
}

axis_levels_for_matrix <- function(df) {
  df |>
    dplyr::distinct(axis_label, axis_order) |>
    dplyr::arrange(dplyr::desc(axis_order)) |>
    dplyr::pull(axis_label) |>
    unique()
}

# ==========================================================
# 4. Figure 2 — Synthetic validation heatmap
# ==========================================================

make_synthetic_validation_data <- function() {
  cached_source <- file.path(
    figure_source_dir,
    "Figure_2_Source_Synthetic_Validation_Heatmap.csv"
  )

  if (file.exists(cached_source)) {
    message("Using cached Figure 2 source: ", cached_source)

    cached_df <- readr::read_csv(
      cached_source,
      show_col_types = FALSE,
      progress = FALSE
    ) |>
      clean_names()

    if (!("n" %in% names(cached_df))) {
      cached_df$n <- NA_real_
    }

    return(
      cached_df |>
        dplyr::mutate(
          matrix = factor(matrix, levels = matrix_labels),
          scenario = factor(as.character(scenario), levels = scenario_levels),
          assigned_grade = factor(as.character(assigned_grade), levels = grade_levels),
          proportion = parse_num(proportion),
          n = parse_num(n),
          label = dplyr::if_else(
            proportion >= 0.005,
            scales::percent(proportion, accuracy = 0.1),
            ""
          )
        )
    )
  }

  dist_table <- read_table_clean("Table_Synthetic_Validation_Grade_Distribution", optional = TRUE)

  if (!is.null(dist_table)) {
    df <- dist_table

    matrix_col <- find_col(
      df,
      c("matrix", "matrix_type", "biospecimen_matrix", "sample_matrix"),
      label = "matrix column"
    )

    scenario_col <- find_col(
      df,
      c(
        "scenario",
        "validation_scenario",
        "synthetic_validation_scenario",
        "expected_scenario",
        "profile_scenario"
      ),
      label = "scenario column"
    )

    grade_col <- find_col(
      df,
      c(
        "final_grade",
        "assigned_grade",
        "assigned_rcs_grade",
        "rcs_grade",
        "grade",
        "score_based_grade"
      ),
      label = "assigned grade column"
    )

    n_col <- find_col(
      df,
      c("n", "count", "profiles", "frequency", "n_profiles"),
      required = FALSE,
      label = "count column"
    )

    prop_col <- find_col(
      df,
      c("proportion", "prop", "percentage", "percent"),
      required = FALSE,
      label = "proportion column"
    )

    tmp <- df |>
      dplyr::transmute(
        matrix = normalize_matrix(.data[[matrix_col]]),
        scenario = normalize_scenario(.data[[scenario_col]]),
        assigned_grade = normalize_grade(.data[[grade_col]]),
        n = if (!is.na(n_col)) parse_num(.data[[n_col]]) else NA_real_,
        proportion_raw = if (!is.na(prop_col)) parse_num(.data[[prop_col]]) else NA_real_
      )

    if (all(is.na(tmp$n)) && any(!is.na(tmp$proportion_raw))) {
      tmp <- tmp |>
        dplyr::mutate(
          proportion = dplyr::if_else(
            proportion_raw > 1,
            proportion_raw / 100,
            proportion_raw
          ),
          n = NA_real_
        )
    } else {
      tmp <- tmp |>
        dplyr::group_by(matrix, scenario, assigned_grade) |>
        dplyr::summarise(n = sum(n, na.rm = TRUE), .groups = "drop") |>
        dplyr::group_by(matrix, scenario) |>
        dplyr::mutate(proportion = n / sum(n, na.rm = TRUE)) |>
        dplyr::ungroup()
    }

  } else {
    cohort <- read_table_clean("Synthetic_Cohort_RCS", optional = FALSE)

    matrix_col <- find_col(
      cohort,
      c("matrix", "matrix_type", "biospecimen_matrix", "sample_matrix"),
      label = "matrix column"
    )

    scenario_col <- find_col(
      cohort,
      c(
        "scenario",
        "validation_scenario",
        "synthetic_validation_scenario",
        "expected_scenario",
        "profile_scenario"
      ),
      label = "scenario column"
    )

    grade_col <- find_col(
      cohort,
      c("final_grade", "assigned_grade", "assigned_rcs_grade", "rcs_grade", "grade"),
      label = "assigned grade column"
    )

    tmp <- cohort |>
      dplyr::transmute(
        matrix = normalize_matrix(.data[[matrix_col]]),
        scenario = normalize_scenario(.data[[scenario_col]]),
        assigned_grade = normalize_grade(.data[[grade_col]])
      ) |>
      dplyr::count(matrix, scenario, assigned_grade, name = "n") |>
      dplyr::group_by(matrix, scenario) |>
      dplyr::mutate(proportion = n / sum(n)) |>
      dplyr::ungroup()
  }

  tmp |>
    dplyr::mutate(
      matrix = factor(matrix, levels = matrix_levels, labels = matrix_labels),
      scenario = factor(scenario, levels = scenario_levels),
      assigned_grade = factor(assigned_grade, levels = grade_levels)
    ) |>
    tidyr::complete(
      matrix,
      scenario,
      assigned_grade,
      fill = list(n = 0, proportion = 0)
    ) |>
    dplyr::mutate(
      label = dplyr::if_else(
        proportion >= 0.005,
        scales::percent(proportion, accuracy = 0.1),
        ""
      )
    )
}

fig2_df <- make_synthetic_validation_data()

readr::write_csv(
  fig2_df,
  file.path(figure_source_dir, "Figure_2_Source_Synthetic_Validation_Heatmap.csv")
)

p2 <- ggplot2::ggplot(
  fig2_df,
  ggplot2::aes(x = scenario, y = assigned_grade, fill = proportion)
) +
  ggplot2::geom_tile(colour = "white", linewidth = 0.8) +
  ggplot2::geom_text(
    ggplot2::aes(label = label),
    size = 3.4,
    colour = "#222222",
    lineheight = 0.9
  ) +
  ggplot2::facet_wrap(~matrix, nrow = 1) +
  ggplot2::scale_x_discrete(
    labels = scenario_labels_manual,
    drop = FALSE
  ) +
  ggplot2::scale_y_discrete(
    limits = rev(grade_levels),
    drop = FALSE
  ) +
  ggplot2::scale_fill_gradient(
    low = "#EFF4FF",
    high = "#4589FF",
    limits = c(0, 1),
    labels = scales::percent_format(accuracy = 1),
    name = "Proportion",
    guide = ggplot2::guide_colorbar(
      title.position = "top",
      title.hjust = 0.5,
      label.position = "bottom",
      barwidth = grid::unit(5.2, "cm"),
      barheight = grid::unit(0.35, "cm")
    )
  ) +
  ggplot2::labs(
    x = "Synthetic validation scenario",
    y = "Assigned RCS grade"
  ) +
  theme_rcs(base_size = 13) +
  ggplot2::theme(
    panel.grid = ggplot2::element_blank(),
    axis.text.x = ggplot2::element_text(size = 11.5, lineheight = 0.90),
    axis.text.y = ggplot2::element_text(size = 10.4),
    axis.title.x = ggplot2::element_text(margin = ggplot2::margin(t = 10)),
    axis.title.y = ggplot2::element_text(margin = ggplot2::margin(r = 10)),
    legend.position = "bottom",
    legend.title = ggplot2::element_text(size = 10.2, margin = ggplot2::margin(b = 4)),
    legend.text = ggplot2::element_text(size = 9.8),
    legend.margin = ggplot2::margin(t = 8, b = 10),
    legend.box.margin = ggplot2::margin(t = 4, b = 8),
    plot.margin = ggplot2::margin(t = 18, r = 30, b = 38, l = 30)
  )

save_figure(
  p2,
  "Figure_2_Synthetic_Validation_Heatmap",
  width = 9.0,
  height = 6.2
)

# ==========================================================
# 5. Figure 3 — Combinatorial distribution
# ==========================================================

make_combinatorial_data <- function() {
  cached_source <- file.path(
    figure_source_dir,
    "Figure_3_Source_Combinatorial_Distribution.csv"
  )

  if (file.exists(cached_source)) {
    message("Using cached Figure 3 source: ", cached_source)

    return(
      readr::read_csv(cached_source, show_col_types = FALSE, progress = FALSE) |>
        clean_names() |>
        dplyr::mutate(
          matrix = factor(matrix, levels = matrix_labels),
          grade = factor(as.character(grade), levels = grade_levels),
          n = parse_num(n),
          proportion = parse_num(proportion),
          label = dplyr::if_else(
            is.na(label) | label == "",
            paste0(scales::percent(proportion, accuracy = 0.1), "\n", "n=", scales::comma(n)),
            as.character(label)
          )
        )
    )
  }

  df <- read_table_clean("Table_Combinatorial_Grade_Distribution", optional = FALSE)

  matrix_col <- find_col(
    df,
    c("matrix", "matrix_type", "biospecimen_matrix", "sample_matrix"),
    label = "matrix column"
  )

  grade_col <- find_col(
    df,
    c("grade", "final_grade", "score_based_grade", "assigned_grade", "rcs_grade"),
    label = "grade column"
  )

  n_col <- find_col(
    df,
    c("n", "count", "profiles", "frequency", "n_profiles"),
    label = "count column"
  )

  prop_col <- find_col(
    df,
    c("proportion", "prop", "percentage", "percent"),
    required = FALSE,
    label = "proportion column"
  )

  tmp <- df |>
    dplyr::transmute(
      matrix = normalize_matrix(.data[[matrix_col]]),
      grade = normalize_grade(.data[[grade_col]]),
      n = parse_num(.data[[n_col]]),
      proportion_raw = if (!is.na(prop_col)) parse_num(.data[[prop_col]]) else NA_real_
    )

  if (any(!is.na(tmp$proportion_raw))) {
    tmp <- tmp |>
      dplyr::mutate(
        proportion = dplyr::if_else(
          proportion_raw > 1,
          proportion_raw / 100,
          proportion_raw
        )
      )
  } else {
    tmp <- tmp |>
      dplyr::group_by(matrix) |>
      dplyr::mutate(proportion = n / sum(n, na.rm = TRUE)) |>
      dplyr::ungroup()
  }

  tmp |>
    dplyr::mutate(
      matrix = factor(matrix, levels = matrix_levels, labels = matrix_labels),
      grade = factor(grade, levels = grade_levels),
      label = paste0(
        scales::percent(proportion, accuracy = 0.1),
        "\n",
        "n=",
        scales::comma(n)
      )
    ) |>
    tidyr::complete(
      matrix,
      grade,
      fill = list(n = 0, proportion = 0, label = "")
    )
}

fig3_df <- make_combinatorial_data()

readr::write_csv(
  fig3_df,
  file.path(figure_source_dir, "Figure_3_Source_Combinatorial_Distribution.csv")
)

p3 <- ggplot2::ggplot(
  fig3_df,
  ggplot2::aes(x = grade, y = proportion, colour = grade)
) +
  ggplot2::geom_segment(
    ggplot2::aes(xend = grade, y = 0, yend = proportion),
    linewidth = 1.8,
    alpha = 0.9
  ) +
  ggplot2::geom_point(size = 4.2, alpha = 0.95) +
  ggplot2::geom_text(
    ggplot2::aes(label = label),
    vjust = -0.55,
    size = 3.25,
    colour = "#222222",
    lineheight = 0.9
  ) +
  ggplot2::facet_wrap(~matrix, nrow = 1) +
  ggplot2::scale_y_continuous(
    labels = function(x) {
      dplyr::if_else(
        x < 0,
        "",
        scales::percent(x, accuracy = 1)
      )
    },
    breaks = seq(0, 0.60, by = 0.10),
    limits = c(-0.015, 0.60),
    expand = ggplot2::expansion(mult = c(0, 0.01))
  ) +
  ggplot2::coord_cartesian(
    ylim = c(-0.015, 0.60),
    clip = "off"
  ) +
  ggplot2::scale_colour_manual(
    values = grade_cols_strong,
    breaks = grade_levels,
    limits = grade_levels,
    drop = FALSE,
    guide = "none"
  ) +
  ggplot2::labs(
    x = NULL,
    y = "Proportion of admissible combinatorial profiles"
  ) +
  theme_rcs(base_size = 13) +
  ggplot2::theme(
    axis.text.x = ggplot2::element_text(size = 10.5),
    panel.grid.minor = ggplot2::element_blank(),
    plot.margin = ggplot2::margin(t = 18, r = 26, b = 30, l = 26)
  )

save_figure(
  p3,
  "Figure_3_Combinatorial_Distribution_Admissible_Grades",
  width = 8.8,
  height = 6.0
)

# ==========================================================
# 6. Figure 4 — Threshold-transition stability summary
# ==========================================================
#
# CMPB/Elsevier rationale:
#   The previous version displayed the full perturbation-by-threshold matrix
#   inside the main figure, which made the image too dense for journal review.
#   This version generates a concise main figure showing the number of
#   perturbation scenarios, out of five, in which each isolated axis reached
#   each grade-transition threshold. The full matrix is preserved as a source
#   CSV for auditability and supplementary use.
# ==========================================================

make_figure4_data <- function() {
  summary_path <- file.path(
    figure_source_dir,
    "Figure_4_Source_Threshold_Transition_Summary.csv"
  )

  full_path <- file.path(
    figure_source_dir,
    "Figure_4_Source_Full_Threshold_Crossing_Matrix.csv"
  )

  old_detail_path <- file.path(
    figure_source_dir,
    "Figure_4_Source_Panel_A_Threshold_Crossing_Matrix.csv"
  )

  if (file.exists(summary_path)) {
    message("Using cached Figure 4 summary source: ", summary_path)

    summary_df <- readr::read_csv(
      summary_path,
      show_col_types = FALSE,
      progress = FALSE
    ) |>
      clean_names()

    if ("transition_label" %in% names(summary_df)) {
      transition_values <- as.character(summary_df$transition_label)
    } else if ("threshold_transition" %in% names(summary_df)) {
      transition_values <- as.character(summary_df$threshold_transition)
    } else {
      transition_values <- rep(NA_character_, nrow(summary_df))
    }

    if (!("total_n" %in% names(summary_df))) {
      summary_df$total_n <- 5
    }

    if (!("reached_label" %in% names(summary_df))) {
      summary_df$reached_label <- NA_character_
    }

    summary_df$transition_label <- transition_values

    # Normalize expected columns if they already exist.
    summary_df <- summary_df |>
      dplyr::mutate(
        matrix = as.character(matrix),
        matrix = dplyr::case_when(
          stringr::str_detect(tolower(matrix), "fluid") ~ "Fluid biospecimens",
          stringr::str_detect(tolower(matrix), "solid") ~ "Solid biospecimens",
          TRUE ~ matrix
        ),
        transition_label = stringr::str_replace_all(transition_label, "A to B|A--B|A-B", "A\u2192B"),
        transition_label = stringr::str_replace_all(transition_label, "B to C|B--C|B-C", "B\u2192C"),
        transition_label = stringr::str_replace_all(transition_label, "C to D|C--D|C-D", "C\u2192D"),
        transition_label = stringr::str_replace_all(transition_label, "D to E|D--E|D-E", "D\u2192E"),
        reached_n = parse_num(reached_n),
        total_n = parse_num(total_n),
        reached_label = dplyr::if_else(
          is.na(reached_label) | reached_label == "",
          paste0(reached_n, "/", total_n),
          as.character(reached_label)
        )
      )

    return(summary_df)
  }

  if (file.exists(full_path)) {
    message("Using cached Figure 4 full source: ", full_path)

    full_df <- readr::read_csv(
      full_path,
      show_col_types = FALSE,
      progress = FALSE
    ) |>
      clean_names()
  } else if (file.exists(old_detail_path)) {
    message("Using legacy Figure 4 source: ", old_detail_path)

    full_df <- readr::read_csv(
      old_detail_path,
      show_col_types = FALSE,
      progress = FALSE
    ) |>
      clean_names()
  } else {
    stop(
      "No Figure 4 source table found. Expected one of: ",
      summary_path, " ; ", full_path, " ; ", old_detail_path
    )
  }

  # Normalize detailed source columns.
  matrix_col <- find_col(full_df, c("matrix"), label = "Figure 4 matrix column")
  axis_col <- find_col(full_df, c("axis"), required = FALSE, label = "Figure 4 axis column")
  axis_label_col <- find_col(full_df, c("axis_label"), label = "Figure 4 axis label column")
  axis_order_col <- find_col(full_df, c("axis_order"), label = "Figure 4 axis order column")
  transition_col <- find_col(
    full_df,
    c("threshold_transition", "transition", "grade_transition"),
    label = "Figure 4 transition column"
  )
  transition_label_col <- find_col(
    full_df,
    c("transition_label"),
    required = FALSE,
    label = "Figure 4 transition label column"
  )
  reached_col <- find_col(full_df, c("reached"), label = "Figure 4 reached column")
  severity_col <- find_col(
    full_df,
    c("severity_required", "severity_plot"),
    required = FALSE,
    label = "Figure 4 severity column"
  )

  summary_df <- full_df |>
    dplyr::transmute(
      matrix = .data[[matrix_col]],
      axis = if (!is.na(axis_col)) as.character(.data[[axis_col]]) else as.character(.data[[axis_label_col]]),
      axis_label = as.character(.data[[axis_label_col]]),
      axis_order = parse_num(.data[[axis_order_col]]),
      threshold_transition = as.character(.data[[transition_col]]),
      transition_label = if (!is.na(transition_label_col)) {
        as.character(.data[[transition_label_col]])
      } else {
        as.character(.data[[transition_col]])
      },
      reached = as.logical(.data[[reached_col]]),
      severity_required = if (!is.na(severity_col)) parse_num(.data[[severity_col]]) else NA_real_
    ) |>
    dplyr::mutate(
      matrix = dplyr::case_when(
        stringr::str_detect(tolower(as.character(matrix)), "fluid") ~ "Fluid biospecimens",
        stringr::str_detect(tolower(as.character(matrix)), "solid") ~ "Solid biospecimens",
        TRUE ~ as.character(matrix)
      ),
      transition_label = stringr::str_replace_all(transition_label, "A to B|A--B|A-B", "A\u2192B"),
      transition_label = stringr::str_replace_all(transition_label, "B to C|B--C|B-C", "B\u2192C"),
      transition_label = stringr::str_replace_all(transition_label, "C to D|C--D|C-D", "C\u2192D"),
      transition_label = stringr::str_replace_all(transition_label, "D to E|D--E|D-E", "D\u2192E")
    ) |>
    dplyr::group_by(
      matrix,
      axis,
      axis_label,
      axis_order,
      threshold_transition,
      transition_label
    ) |>
    dplyr::summarise(
      reached_n = sum(reached, na.rm = TRUE),
      total_n = dplyr::n(),
      min_severity_reached = ifelse(
        any(reached),
        min(severity_required[reached], na.rm = TRUE),
        NA_real_
      ),
      .groups = "drop"
    ) |>
    dplyr::mutate(
      reached_label = paste0(reached_n, "/", total_n)
    )

  readr::write_csv(
    summary_df,
    summary_path
  )

  summary_df
}

fig4_summary <- make_figure4_data()

# Clean labels for main figure.
fig4_summary <- fig4_summary |>
  dplyr::mutate(
    matrix = factor(
      matrix,
      levels = c("Fluid biospecimens", "Solid biospecimens")
    ),
    transition_label = factor(
      transition_label,
      levels = c("A\u2192B", "B\u2192C", "C\u2192D", "D\u2192E")
    ),
    reached_n = parse_num(reached_n),
    total_n = parse_num(total_n),
    reached_label = paste0(reached_n, "/", total_n)
  )

axis_levels_fig4 <- fig4_summary |>
  dplyr::distinct(matrix, axis_label, axis_order) |>
  dplyr::arrange(matrix, dplyr::desc(axis_order))

fig4_summary <- fig4_summary |>
  dplyr::left_join(
    axis_levels_fig4,
    by = c("matrix", "axis_label", "axis_order")
  ) |>
  dplyr::group_by(matrix) |>
  dplyr::mutate(
    axis_label = factor(
      axis_label,
      levels = unique(axis_label[order(dplyr::desc(axis_order))])
    )
  ) |>
  dplyr::ungroup()

readr::write_csv(
  fig4_summary,
  file.path(figure_source_dir, "Figure_4_Source_Threshold_Transition_Summary.csv")
)

p4 <- ggplot2::ggplot(
  fig4_summary,
  ggplot2::aes(
    x = transition_label,
    y = axis_label,
    fill = reached_n
  )
) +
  ggplot2::geom_tile(
    colour = "white",
    linewidth = 1.0
  ) +
  ggplot2::geom_text(
    ggplot2::aes(label = reached_label),
    size = 4.7,
    fontface = "bold",
    colour = "#222222"
  ) +
  ggplot2::facet_wrap(
    ~matrix,
    nrow = 1,
    scales = "free_y"
  ) +
  ggplot2::scale_fill_gradient(
    low = "#F4F4F4",
    high = "#4589FF",
    limits = c(0, 5),
    breaks = 0:5,
    name = "Perturbation scenarios reached",
    guide = ggplot2::guide_colorbar(
      title.position = "top",
      title.hjust = 0.5,
      label.position = "bottom",
      barwidth = grid::unit(6.4, "cm"),
      barheight = grid::unit(0.42, "cm")
    )
  ) +
  ggplot2::labs(
    x = "RCS grade-transition threshold",
    y = NULL
  ) +
  theme_rcs(base_size = 14) +
  ggplot2::theme(
    panel.grid = ggplot2::element_blank(),
    panel.spacing.x = grid::unit(2.2, "lines"),
    axis.text.x = ggplot2::element_text(
      size = 12,
      face = "bold",
      colour = "#222222"
    ),
    axis.text.y = ggplot2::element_text(
      size = 11.5,
      colour = "#222222"
    ),
    axis.title.x = ggplot2::element_text(
      size = 13,
      margin = ggplot2::margin(t = 12)
    ),
    strip.text = ggplot2::element_text(
      size = 14,
      face = "bold",
      colour = "#222222",
      margin = ggplot2::margin(b = 8)
    ),
    legend.position = "bottom",
    legend.title = ggplot2::element_text(size = 11.5),
    legend.text = ggplot2::element_text(size = 10.5),
    legend.margin = ggplot2::margin(t = 8, b = 8),
    legend.box.margin = ggplot2::margin(t = 8, b = 8),
    plot.margin = ggplot2::margin(t = 22, r = 28, b = 26, l = 28)
  )

save_figure(
  p4,
  "Figure_4_Threshold_Stability_Grade_Transitions",
  width = 10.0,
  height = 6.4
)


# ==========================================================
# 7. Figure 5 — Runtime scalability
# ==========================================================

make_runtime_data <- function() {
  cached_raw <- file.path(
    figure_source_dir,
    "Figure_5_Source_Runtime_Raw.csv"
  )

  cached_summary <- file.path(
    figure_source_dir,
    "Figure_5_Source_Runtime_Summary.csv"
  )

  if (file.exists(cached_raw) && file.exists(cached_summary)) {
    message("Using cached Figure 5 source tables.")

    raw_plot <- readr::read_csv(cached_raw, show_col_types = FALSE, progress = FALSE) |>
      clean_names()

    summary_plot <- readr::read_csv(cached_summary, show_col_types = FALSE, progress = FALSE) |>
      clean_names()

    raw_plot <- raw_plot |>
      dplyr::mutate(
        n_profiles = parse_num(n_profiles),
        elapsed_seconds = parse_num(elapsed_seconds)
      )

    summary_plot <- summary_plot |>
      dplyr::mutate(
        n_profiles = parse_num(n_profiles),
        mean_elapsed_seconds = if ("mean_elapsed_seconds" %in% names(summary_plot)) {
          parse_num(mean_elapsed_seconds)
        } else {
          NA_real_
        },
        mean_cost_us = parse_num(mean_cost_us)
      )

    lm_fit <- stats::lm(elapsed_seconds ~ n_profiles, data = raw_plot)
    r2 <- summary(lm_fit)$r.squared
    slope <- unname(stats::coef(lm_fit)[["n_profiles"]])

    return(
      list(
        raw = raw_plot,
        summary = summary_plot,
        r2 = r2,
        slope = slope
      )
    )
  }

  summary_df <- read_table_clean("Table_Runtime_Benchmark_Summary", optional = TRUE)
  raw_df <- read_table_clean("Table_Runtime_Benchmark_Raw", optional = TRUE)

  if (!is.null(raw_df)) {
    n_col <- find_col(
      raw_df,
      c("n_profiles", "profiles", "n_records", "records", "n", "cohort_size", "sample_size"),
      label = "runtime profile-count column"
    )

    elapsed_col <- find_col(
      raw_df,
      c(
        "elapsed_seconds",
        "elapsed_sec",
        "elapsed_time",
        "time_seconds",
        "time_sec",
        "runtime_seconds",
        "seconds"
      ),
      label = "runtime elapsed-time column"
    )

    raw_plot <- raw_df |>
      dplyr::transmute(
        n_profiles = parse_num(.data[[n_col]]),
        elapsed_seconds = parse_num(.data[[elapsed_col]])
      ) |>
      dplyr::filter(is.finite(n_profiles), is.finite(elapsed_seconds))

  } else if (!is.null(summary_df)) {
    n_col <- find_col(
      summary_df,
      c("n_profiles", "profiles", "n_records", "records", "n", "cohort_size", "sample_size"),
      label = "runtime profile-count column"
    )

    elapsed_col <- find_col(
      summary_df,
      c(
        "mean_elapsed_seconds",
        "mean_elapsed_sec",
        "elapsed_seconds",
        "elapsed_sec",
        "mean_seconds",
        "runtime_seconds",
        "seconds"
      ),
      label = "runtime elapsed-time column"
    )

    raw_plot <- summary_df |>
      dplyr::transmute(
        n_profiles = parse_num(.data[[n_col]]),
        elapsed_seconds = parse_num(.data[[elapsed_col]])
      ) |>
      dplyr::filter(is.finite(n_profiles), is.finite(elapsed_seconds))

  } else {
    stop("Runtime benchmark tables were not found.")
  }

  summary_plot <- raw_plot |>
    dplyr::group_by(n_profiles) |>
    dplyr::summarise(
      mean_elapsed_seconds = mean(elapsed_seconds, na.rm = TRUE),
      .groups = "drop"
    ) |>
    dplyr::mutate(
      mean_cost_us = mean_elapsed_seconds / n_profiles * 1e6
    )

  if (!is.null(summary_df)) {
    n_col_sum <- find_col(
      summary_df,
      c("n_profiles", "profiles", "n_records", "records", "n", "cohort_size", "sample_size"),
      required = FALSE,
      label = "summary profile-count column"
    )

    cost_col_sum <- find_col(
      summary_df,
      c(
        "mean_per_sample_microsec",
        "mean_per_profile_microsec",
        "mean_cost_us",
        "mean_cost_microsec",
        "per_sample_microsec",
        "per_profile_microsec",
        "microseconds_per_sample",
        "microseconds_per_profile"
      ),
      required = FALSE,
      label = "summary per-profile cost column"
    )

    if (!is.na(n_col_sum) && !is.na(cost_col_sum)) {
      cost_from_summary <- summary_df |>
        dplyr::transmute(
          n_profiles = parse_num(.data[[n_col_sum]]),
          mean_cost_us_summary = parse_num(.data[[cost_col_sum]])
        ) |>
        dplyr::filter(is.finite(n_profiles), is.finite(mean_cost_us_summary)) |>
        dplyr::group_by(n_profiles) |>
        dplyr::summarise(
          mean_cost_us_summary = mean(mean_cost_us_summary, na.rm = TRUE),
          .groups = "drop"
        )

      if (nrow(cost_from_summary) > 0) {
        summary_plot <- summary_plot |>
          dplyr::left_join(cost_from_summary, by = "n_profiles") |>
          dplyr::mutate(
            mean_cost_us = dplyr::coalesce(mean_cost_us_summary, mean_cost_us)
          ) |>
          dplyr::select(-mean_cost_us_summary)
      }
    }
  }

  lm_fit <- stats::lm(elapsed_seconds ~ n_profiles, data = raw_plot)
  r2 <- summary(lm_fit)$r.squared
  slope <- unname(stats::coef(lm_fit)[["n_profiles"]])

  list(
    raw = raw_plot,
    summary = summary_plot,
    r2 = r2,
    slope = slope
  )
}

runtime <- make_runtime_data()

readr::write_csv(
  runtime$raw,
  file.path(figure_source_dir, "Figure_5_Source_Runtime_Raw.csv")
)

readr::write_csv(
  runtime$summary,
  file.path(figure_source_dir, "Figure_5_Source_Runtime_Summary.csv")
)

r2_label <- paste0(
  "Linear fit R\u00b2 = ",
  format(round(runtime$r2, 4), nsmall = 4)
)

mean_cost_label <- paste0(
  "Mean cost \u2248 ",
  format(round(mean(runtime$summary$mean_cost_us, na.rm = TRUE), 2), nsmall = 2),
  " \u00b5s/profile"
)

x_runtime_anno <- min(runtime$raw$n_profiles, na.rm = TRUE) +
  0.04 * diff(range(runtime$raw$n_profiles, na.rm = TRUE))

y_runtime_anno <- max(runtime$raw$elapsed_seconds, na.rm = TRUE) -
  0.08 * diff(range(runtime$raw$elapsed_seconds, na.rm = TRUE))

x_cost_anno <- min(runtime$summary$n_profiles, na.rm = TRUE) +
  0.05 * diff(range(runtime$summary$n_profiles, na.rm = TRUE))

y_cost_anno <- max(runtime$summary$mean_cost_us, na.rm = TRUE) -
  0.12 * diff(range(runtime$summary$mean_cost_us, na.rm = TRUE))

p5a <- ggplot2::ggplot(
  runtime$raw,
  ggplot2::aes(x = n_profiles, y = elapsed_seconds)
) +
  ggplot2::geom_point(
    colour = "#4589FF",
    size = 2.3,
    alpha = 0.75
  ) +
  ggplot2::geom_smooth(
    method = "lm",
    formula = y ~ x,
    se = FALSE,
    colour = "#525252",
    linewidth = 0.8
  ) +
  ggplot2::annotate(
    "text",
    x = x_runtime_anno,
    y = y_runtime_anno,
    label = r2_label,
    hjust = 0,
    size = 3.7,
    colour = "#222222"
  ) +
  ggplot2::scale_x_continuous(
    labels = profile_label,
    expand = ggplot2::expansion(mult = c(0.04, 0.05))
  ) +
  ggplot2::labs(
    title = "A. Batch elapsed time",
    x = NULL,
    y = "Elapsed time (seconds)"
  ) +
  theme_rcs(base_size = 13) +
  ggplot2::theme(
    plot.title = ggplot2::element_text(face = "bold", hjust = 0, size = 13),
    legend.position = "none",
    plot.margin = ggplot2::margin(t = 10, r = 18, b = 8, l = 18)
  )

p5b <- ggplot2::ggplot(
  runtime$summary,
  ggplot2::aes(x = n_profiles, y = mean_cost_us)
) +
  ggplot2::geom_line(
    colour = "#BE95FF",
    linewidth = 0.9
  ) +
  ggplot2::geom_point(
    colour = "#8A3FFC",
    fill = "#BE95FF",
    size = 2.5,
    alpha = 0.85
  ) +
  ggplot2::annotate(
    "text",
    x = x_cost_anno,
    y = y_cost_anno,
    label = mean_cost_label,
    hjust = 0,
    size = 3.6,
    colour = "#222222"
  ) +
  ggplot2::scale_x_continuous(
    labels = profile_label,
    expand = ggplot2::expansion(mult = c(0.04, 0.05))
  ) +
  ggplot2::labs(
    title = "B. Mean per-profile computational cost",
    x = "Number of biospecimen profiles",
    y = "Mean cost per profile (\u00b5s)"
  ) +
  theme_rcs(base_size = 13) +
  ggplot2::theme(
    plot.title = ggplot2::element_text(face = "bold", hjust = 0, size = 13),
    legend.position = "none",
    plot.margin = ggplot2::margin(t = 8, r = 18, b = 24, l = 18)
  )

p5 <- (p5a / p5b) +
  patchwork::plot_layout(heights = c(1, 1)) &
  ggplot2::theme(
    plot.background = ggplot2::element_rect(fill = "white", colour = NA),
    plot.margin = ggplot2::margin(t = 12, r = 22, b = 18, l = 22)
  )

save_figure(
  p5,
  "Figure_5_Runtime_Scalability",
  width = 9.2,
  height = 6.8
)

# ==========================================================
# 8. Supplementary audit tables
# ==========================================================

supplementary_index <- tibble::tibble(
  file_name = character(),
  source_tables = character(),
  description = character(),
  status = character()
)

add_supplementary_index <- function(file_name, source_tables, description, status) {
  supplementary_index <<- dplyr::bind_rows(
    supplementary_index,
    tibble::tibble(
      file_name = file_name,
      source_tables = source_tables,
      description = description,
      status = status
    )
  )
}

write_combined_supplementary_table <- function(stems, out_file, description) {
  dfs <- list()
  found <- character()

  for (stem in stems) {
    raw_df <- read_table_raw_by_stem(stem)

    if (!is.null(raw_df)) {
      found <- c(found, stem)

      raw_df <- raw_df |>
        dplyr::mutate(
          source_table = stem,
          .before = 1
        ) |>
        dplyr::mutate(
          dplyr::across(dplyr::everything(), as.character)
        )

      dfs[[stem]] <- raw_df
    }
  }

  if (length(dfs) == 0) {
    add_supplementary_index(
      file_name = out_file,
      source_tables = paste(stems, collapse = "; "),
      description = description,
      status = "not generated; source table not found"
    )
    message("Skipped supplementary table because source table was not found: ", out_file)
    return(invisible(NULL))
  }

  combined <- dplyr::bind_rows(dfs)

  readr::write_csv(
    combined,
    file.path(supplementary_dir, out_file)
  )

  add_supplementary_index(
    file_name = out_file,
    source_tables = paste(found, collapse = "; "),
    description = description,
    status = "generated"
  )

  message("Generated supplementary table: ", out_file)
}

write_combined_supplementary_table(
  stems = c("Table_Property_Based_Checks"),
  out_file = "Additional_File_S4_Property_Based_Logical_Checks.csv",
  description = "Property-based logical checks validating deterministic behaviour, bounded penalties, monotonicity, matrix-specific axes, and governance override."
)

write_combined_supplementary_table(
  stems = c(
    "Table_Validation_Summary",
    "Table_Internal_Calibration_Index",
    "Table_Internal_Calibration_By_Matrix",
    "Table_Internal_Calibration_By_Scenario"
  ),
  out_file = "Additional_File_S5_Synthetic_Validation_And_Internal_Calibration.csv",
  description = "Synthetic validation summary and internal calibration agreement tables."
)

write_combined_supplementary_table(
  stems = c(
    "Table_Threshold_Margin_Analysis",
    "Table_Threshold_Margin_Summary"
  ),
  out_file = "Additional_File_S6_Threshold_Margin_Analysis.csv",
  description = "Threshold-margin analysis quantifying proximity of score-derived classifications to grade boundaries."
)

write_combined_supplementary_table(
  stems = c("Table_Governance_Sensitivity"),
  out_file = "Additional_File_S7_Governance_Failure_Sensitivity_Override.csv",
  description = "Governance-failure sensitivity table demonstrating non-compensable override to Grade E."
)

write_combined_supplementary_table(
  stems = c(
    "Table_Global_Sensitivity_Ranking",
    "Table_Global_Sensitivity",
    "Table_Global_Sensitivity_Summary",
    "Table_Morris_Sensitivity",
    "Table_Sobol_Sensitivity",
    "Table_Axis_Influence_Summary"
  ),
  out_file = "Additional_File_S8_Global_Sensitivity_And_Axis_Influence.csv",
  description = "Global sensitivity and axis-influence summaries. These tables describe relative contribution to penalty accumulation, not threshold-crossing behaviour."
)

write_combined_supplementary_table(
  stems = c(
    "Table_Weight_Perturbation_Sensitivity",
    "Table_Weight_Perturbation_Robustness",
    "Table_Weight_Perturbation_Summary"
  ),
  out_file = "Additional_File_S9_Weight_Perturbation_Robustness.csv",
  description = "Weight-perturbation robustness summaries for RCS outputs."
)

write_combined_supplementary_table(
  stems = c(
    "Table_Ablation_Analysis",
    "Table_Ablation_Summary"
  ),
  out_file = "Additional_File_S10_Ablation_Analysis.csv",
  description = "Ablation analysis of governance-aware RCS components."
)

write_combined_supplementary_table(
  stems = c(
    "Table_Runtime_Benchmark_Summary",
    "Table_Runtime_Linear_Fit"
  ),
  out_file = "Additional_File_S11_Runtime_Benchmark_Summary.csv",
  description = "Runtime benchmark summary and linear-fit diagnostics."
)

readr::write_csv(
  supplementary_index,
  file.path(supplementary_dir, "Supplementary_Output_Index.csv")
)

# ==========================================================
# 9. Main output index
# ==========================================================

main_output_index <- tibble::tribble(
  ~item, ~file_base, ~type, ~description,
  "Figure 2", "Figure_2_Synthetic_Validation_Heatmap", "main figure", "Synthetic validation of expected versus assigned RCS grades.",
  "Figure 3", "Figure_3_Combinatorial_Distribution_Admissible_Grades", "main figure", "Theoretical admissible combinatorial score-derived grade distribution.",
  "Figure 4", "Figure_4_Threshold_Stability_Grade_Transitions", "main figure", "Threshold-transition stability summary under axis-weight perturbation.",
  "Figure 5", "Figure_5_Runtime_Scalability", "main figure", "Runtime scalability and mean per-profile computational cost.",
  "Supplementary figures", "not generated", "supplementary figure", "No supplementary figures generated by design; non-main evidence exported as supplementary tables.",
  "Additional File S4", "Additional_File_S4_Property_Based_Logical_Checks.csv", "supplementary table", "Property-based logical checks.",
  "Additional File S5", "Additional_File_S5_Synthetic_Validation_And_Internal_Calibration.csv", "supplementary table", "Synthetic validation and internal calibration.",
  "Additional File S6", "Additional_File_S6_Threshold_Margin_Analysis.csv", "supplementary table", "Threshold-margin analysis.",
  "Additional File S7", "Additional_File_S7_Governance_Failure_Sensitivity_Override.csv", "supplementary table", "Governance-failure sensitivity and non-compensable override.",
  "Additional File S8", "Additional_File_S8_Global_Sensitivity_And_Axis_Influence.csv", "supplementary table", "Global sensitivity and axis influence.",
  "Additional File S9", "Additional_File_S9_Weight_Perturbation_Robustness.csv", "supplementary table", "Weight-perturbation robustness.",
  "Additional File S10", "Additional_File_S10_Ablation_Analysis.csv", "supplementary table", "Ablation analysis.",
  "Additional File S11", "Additional_File_S11_Runtime_Benchmark_Summary.csv", "supplementary table", "Runtime benchmark summary."
)

readr::write_csv(
  main_output_index,
  file.path(table_dir, "Figure_And_Supplementary_Output_Index.csv")
)

# ==========================================================
# 10. Final report
# ==========================================================

message("==========================================================")
message("Main figure generation completed successfully.")
message("")
message("Generated main figures:")
message("  - Figure_2_Synthetic_Validation_Heatmap.pdf/png")
message("  - Figure_3_Combinatorial_Distribution_Admissible_Grades.pdf/png")
message("  - Figure_4_Threshold_Stability_Grade_Transitions.pdf/png")
message("  - Figure_5_Runtime_Scalability.pdf/png")
message("")
message("Supplementary figures:")
message("  - None generated by design.")
message("")
message("Figure source tables:")
message("  - ", figure_source_dir)
message("")
message("Supplementary audit tables:")
message("  - ", supplementary_dir)
message("")
message("Output index:")
message("  - ", file.path(table_dir, "Figure_And_Supplementary_Output_Index.csv"))
message("==========================================================")
