@echo off
setlocal

where gnuplot >nul 2>&1
if errorlevel 1 (
  echo Error: gnuplot is required and must be available in PATH.
  exit /b 1
)

for %%T in (
  outputs\tables\Table_Synthetic_Validation_Grade_Distribution.csv
  outputs\tables\Table_Combinatorial_Grade_Distribution.csv
  outputs\tables\Table_Threshold_Transition_Detail.csv
  outputs\tables\Table_Benchmark_Runtime_Summary.csv
  outputs\tables\Table_Benchmark_Within_Language_Speedup_Summary.csv
  outputs\tables\Table_Benchmark_CUDA_Speedup_Summary.csv
) do (
  if not exist "%%T" (
    echo Error: missing canonical figure input: %%T
    exit /b 1
  )
)

if not exist outputs\figures mkdir outputs\figures

for %%M in (pdf png) do (
  for %%F in (2 3 4 5 6 7) do (
    echo Generating Figure_%%F.%%M
    gnuplot -e "OUTPUT_MODE='%%M'" "scripts/gnuplot/Figure_%%F.gp"
    if errorlevel 1 exit /b 1
  )
)

echo Figures 2 through 7 generated from canonical sources. Figure 1 is retained as the manuscript conceptual diagram and is not generated by Gnuplot.
endlocal
